kind: ExecutorPlugin
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd
  annotations:
    workflows.argoproj.io/description: |
      This is an Argo CD plugin that allows you to interact with an argocd instance of your choice.
      For examples visit https://github.com/UrielCohen456/argo-workflows-argocd-executor-plugin/examples
    workflows.argoproj.io/version: '>= v3.3'
spec:
  sidecar:
    container:
      name: argocd
      image: crenshawdotdev/argocd-executor-plugin:v0.0.7
      imagePullPolicy: Never
      env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-token
              key: token
        - name: ARGOCD_SERVER
          value: argocd-server.argocd.svc.cluster.local
      ports:
        - containerPort: 3000
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
