apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
spec:
  ttlStrategy:
    secondsAfterCompletion: 300
    secondsAfterFailure: 300
    secondsAfterSuccess: 300
  serviceAccountName: workflow
  entrypoint: main
  templates:
    - name: main
      steps:
      - - name: sync
          template: sync
          arguments:
            parameters:
              - name: apps
                value: |
                  - name: guestbook
      - - name: diff
          template: diff
    - name: sync
      inputs:
        parameters:
          - name: apps
      plugin:
        argocd:
          app:
            sync:
              apps: "{{inputs.parameters.apps}}"
    - name: diff
      plugin:
        argocd:
          # TODO: support other action types, e.g. `cluster` and `repository`.
          app:
            diff:
              app:
                name: guestbook
              revision: 382b85852fa33f13d4987424853c5206b9231ff0
